### ISSUE TITLE
ModuleNotFoundError: No module named 'mt_exceptions'

### ISSUE THREAD

**Issue by bipsen** [gabelev/machine_music#2]
I get this error when I try to run tonal.py. Is it an issue with using Python 3?
```
>>> python tonal.py HarmonicMajor A
Traceback (most recent call last):
    File "tonal.py", line 2, in <module>
        import mingus.core.notes as notes
    File "/Users/bertilipsen/anaconda3/lib/python3.6/site-packages/mingus/core/notes.py", line 29, in <module>
        from mt_exceptions import NoteFormatError, RangeError, FormatError
ModuleNotFoundError: No module named 'mt_exceptions'
```
Thanks!

**Comment by bipsen** [comment]
Ran 2to3 on the mingus source code and I don't get this error anymore. Nothing seems to happen when I run tonal.py though, am I doing something wrong?
Edit: I see tonal.py is just a bunch of classes (apologies for all this, I'm totally new to Python). Is it possible to get the script you used in the video (tonal_script.py)?
